language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dinhminh8x/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dinhminh8x/docker-react npm run test -- --coverage